import { connect, type Socket } from "node:net";
import { createId } from "../shared/ids.js";
import { encodeFrame, NdjsonDecoder } from "../shared/protocol/codec.js";
import type { PiSafeState } from "./types.js";

export interface PiBrokerPrincipal { id: string; kind: "human" | "pi_parent" | "pi_child"; permissions: string[]; agentId?: string; generation?: number; piSessionId?: string; }
interface HelloResult { v: 1; type: "hello_result"; id: string; ok: true; broker: { version: string; status: string; lastEventSeq: number }; principal: PiBrokerPrincipal; limits: { maxLineBytes: number }; }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("BROKER_HELLO_INVALID"); return value as Record<string, unknown>; }
function safeString(value: unknown, max = 256): string { if (typeof value !== "string" || value.length === 0 || Buffer.byteLength(value, "utf8") > max || /[\u0000-\u001f\u007f]/u.test(value)) throw new Error("BROKER_HELLO_INVALID"); return value; }
function validateHelloResult(value: unknown, expectedId: string): HelloResult {
  const frame = record(value); const keys = ["v", "type", "id", "ok", "broker", "principal", "limits", "error"];
  if (Object.keys(frame).some((key) => !keys.includes(key)) || frame.v !== 1 || frame.type !== "hello_result" || frame.id !== expectedId || frame.ok !== true || Object.hasOwn(frame, "error") || !Object.hasOwn(frame, "broker") || !Object.hasOwn(frame, "principal") || !Object.hasOwn(frame, "limits")) throw new Error("BROKER_HELLO_INVALID");
  const broker = record(frame.broker); if (!exactKeys(broker, ["version", "status", "lastEventSeq"]) || !Object.hasOwn(broker, "version") || !Object.hasOwn(broker, "status") || !Object.hasOwn(broker, "lastEventSeq")) throw new Error("BROKER_HELLO_INVALID"); const version = safeString(broker.version); const status = safeString(broker.status); if (!Number.isSafeInteger(broker.lastEventSeq) || (broker.lastEventSeq as number) < 0) throw new Error("BROKER_HELLO_INVALID");
  const principal = record(frame.principal); const principalKeys = ["id", "kind", "permissions", "agentId", "generation", "piSessionId"]; if (Object.keys(principal).some((key) => !principalKeys.includes(key))) throw new Error("BROKER_HELLO_INVALID");
  const kind = principal.kind; if (kind !== "human" && kind !== "pi_parent" && kind !== "pi_child") throw new Error("BROKER_HELLO_INVALID");
  if (!Array.isArray(principal.permissions) || principal.permissions.length > 4096 || principal.permissions.some((permission) => typeof permission !== "string" || permission.length === 0 || Buffer.byteLength(permission, "utf8") > 256)) throw new Error("BROKER_HELLO_INVALID");
  const limits = record(frame.limits); if (!exactKeys(limits, ["maxLineBytes"]) || !Number.isSafeInteger(limits.maxLineBytes) || (limits.maxLineBytes as number) < 1 || (limits.maxLineBytes as number) > 16_777_216) throw new Error("BROKER_HELLO_INVALID");
  const agentId = principal.agentId === undefined ? undefined : safeString(principal.agentId); const piSessionId = principal.piSessionId === undefined ? undefined : safeString(principal.piSessionId); const generation = principal.generation;
  if (generation !== undefined && (!Number.isSafeInteger(generation) || (generation as number) < 1)) throw new Error("BROKER_HELLO_INVALID");
  return { v: 1, type: "hello_result", id: expectedId, ok: true, broker: { version, status, lastEventSeq: broker.lastEventSeq as number }, principal: { id: safeString(principal.id), kind, permissions: [...principal.permissions] as string[], ...(agentId !== undefined ? { agentId } : {}), ...(generation !== undefined ? { generation: generation as number } : {}), ...(piSessionId !== undefined ? { piSessionId } : {}) }, limits: { maxLineBytes: limits.maxLineBytes as number } };
}
export interface PiServerRequest { id: string; method: string; params: Record<string, unknown>; }
export interface PiBrokerClientOptions { socketPath: string; sessionKey: string; agentId?: string; generation?: number; piSessionId: string; token?: string; secret?: string; helloTimeoutMs?: number; requestTimeoutMs?: number; onServerRequest?: (request: PiServerRequest) => Promise<unknown>; onControlRequest?: (request: PiServerRequest) => Promise<unknown>; }
export interface PiRequestOptions { timeoutMs?: number; idempotencyKey?: string; }
const DEFAULT_HELLO_TIMEOUT_MS = 10_000; const DEFAULT_REQUEST_TIMEOUT_MS = 15_000; const MAX_TIMEOUT_MS = 120_000;
function exactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean { return Object.keys(value).every((key) => keys.includes(key)); }
function validResponse(value: Record<string, unknown>): boolean { if (value.v !== 1 || value.type !== "response" || typeof value.id !== "string" || value.id.length === 0 || typeof value.ok !== "boolean" || !exactKeys(value, value.ok ? ["v", "type", "id", "ok", "result"] : ["v", "type", "id", "ok", "error"])) return false; if (value.ok) return Object.hasOwn(value, "result") && !Object.hasOwn(value, "error"); const error = value.error; return !!error && typeof error === "object" && !Array.isArray(error) && exactKeys(error as Record<string, unknown>, ["code", "message"]) && typeof (error as Record<string, unknown>).code === "string" && typeof (error as Record<string, unknown>).message === "string"; }
export class PiBrokerClient {
  #socket: Socket | undefined; #options: PiBrokerClientOptions; #pending = new Map<string, { resolve: (value: unknown) => void; reject: (error: Error) => void }>(); #connected = false; #adapterSeq = 0; #helloId: string | undefined; #principal: PiBrokerPrincipal | undefined; #responseIds = new Set<string>(); #serverRequestIds = new Set<string>();
  constructor(options: PiBrokerClientOptions) { this.#options = options; }
  get principal(): PiBrokerPrincipal | undefined { return this.#principal; }
  bindIdentity(agentId: string, generation: number): void { if (!/^[\x21-\x7e]{1,256}$/u.test(agentId) || !Number.isSafeInteger(generation) || generation < 1) throw new Error("PI_REGISTRATION_IDENTITY_INVALID"); if (this.#principal) this.#principal = { ...this.#principal, agentId, generation }; }
  get connected(): boolean { return this.#connected; }
  async connect(): Promise<unknown> {
    if (this.#connected) return { connected: true };
    const socket = await new Promise<Socket>((resolve, reject) => { const s = connect(this.#options.socketPath); const timer = setTimeout(() => { s.destroy(); reject(new Error("BROKER_TIMEOUT")); }, this.timeout(this.#options.helloTimeoutMs ?? DEFAULT_HELLO_TIMEOUT_MS)); timer.unref?.(); s.once("connect", () => { clearTimeout(timer); resolve(s); }); s.once("error", (error) => { clearTimeout(timer); reject(error); }); });
    this.#socket = socket; this.#responseIds.clear(); this.#serverRequestIds.clear(); const decoder = new NdjsonDecoder<unknown>((value) => value);
    socket.on("data", (data) => { for (const item of decoder.push(data)) { if (!item.ok) { this.failClosed(item.error); continue; } if (typeof item.value !== "object" || item.value === null || Array.isArray(item.value)) { this.failClosed(); continue; } const frame = item.value as Record<string, unknown>; if (typeof frame.id !== "string") { this.failClosed(); continue; } if (frame.type === "server_request") { void this.handleServerRequest(frame); continue; } if (frame.type === "hello_result") { if (frame.id !== this.#helloId) { const waiter = this.#helloId ? this.#pending.get(this.#helloId) : undefined; if (waiter) { this.#pending.delete(this.#helloId!); waiter.reject(new Error("BROKER_HELLO_INVALID")); } socket.destroy(); continue; } const waiter = this.#pending.get(frame.id); if (!waiter) { this.failClosed(); continue; } this.#pending.delete(frame.id); try { waiter.resolve(validateHelloResult(frame, frame.id)); } catch { waiter.reject(new Error("BROKER_HELLO_INVALID")); socket.destroy(); } continue; } if (frame.type !== "response") { this.failClosed(); continue; } if (!validResponse(frame) || this.#responseIds.has(frame.id)) { this.failClosed(); continue; } const waiter = this.#pending.get(frame.id); if (!waiter) { this.failClosed(); continue; } this.#responseIds.add(frame.id); this.#pending.delete(frame.id); if (frame.ok === true) waiter.resolve(frame.result); else waiter.reject(new Error("BROKER_REQUEST_FAILED")); } });
    socket.once("close", () => { this.#connected = false; this.#socket = undefined; for (const waiter of this.#pending.values()) waiter.reject(new Error("AGENT_DISCONNECTED")); this.#pending.clear(); });
    const auth = this.#options.token && this.#options.agentId !== undefined && this.#options.generation !== undefined ? { kind: "agent_token" as const, token: this.#options.token, agentId: this.#options.agentId, generation: this.#options.generation, piSessionId: this.#options.piSessionId } : { kind: "client_secret" as const, ...(this.#options.secret !== undefined ? { secret: this.#options.secret } : {}) };
    const helloId = createId("evt"); this.#helloId = helloId; const hello = await this.raw({ v: 1, type: "hello", id: helloId, client: { kind: this.#options.token && this.#options.agentId !== undefined ? "pi_child" : "pi_parent", name: "pi-herdr-orchestrator", version: "0.1.0", capabilities: ["pi.lifecycle", "pi.controls"] }, sessionKey: this.#options.sessionKey, auth }, this.#options.helloTimeoutMs);
    const accepted = hello as HelloResult; this.#connected = true; this.#principal = accepted.principal; return accepted;
  }
  async request(method: string, params: Record<string, unknown>, options: PiRequestOptions = {}): Promise<unknown> { if (!this.#connected || !this.#socket) throw new Error("AGENT_DISCONNECTED"); const frame = { v: 1, type: "request" as const, id: createId("evt"), method, params, ...(options.idempotencyKey ? { idempotencyKey: options.idempotencyKey } : {}) }; return await this.raw(frame, options.timeoutMs); }
  async register(state: PiSafeState): Promise<{ agentId: string; generation: number; connectionGeneration: number; heartbeatMs: number; permissions: string[] }> { const safeName = process.env.HERDR_AGENT_NAME; const safeState = { activity: state.activity, idle: state.idle, pendingMessages: state.pendingMessages, ...(state.turnIndex !== undefined ? { turnIndex: state.turnIndex } : {}), ...(state.contextPercent !== undefined ? { contextPercent: state.contextPercent } : {}), ...(state.currentTool !== undefined ? { currentTool: state.currentTool } : {}) }; const result = await this.request(this.#options.token ? "agent.register_managed" : "agent.register_adopted", { adapterVersion: "0.1.0", ...(this.#options.agentId ? { agentId: this.#options.agentId, generation: this.#options.generation } : {}), herdr: { paneId: process.env.HERDR_PANE_ID, terminalId: process.env.HERDR_TERMINAL_ID, detectedKind: "pi", ...(safeName && safeName.length <= 256 && !/[\u0000-\u001f\u007f]/u.test(safeName) ? { name: safeName } : {}) }, pi: { sessionId: state.sessionId, capabilities: state.capabilities, state: safeState } }); const value = record(result); if (!exactKeys(value, ["agentId", "generation", "connectionGeneration", "heartbeatMs", "permissions"])) throw new Error("PI_REGISTRATION_IDENTITY_INVALID"); const generationValue = value.generation; const connectionGenerationValue = value.connectionGeneration; const heartbeatMsValue = value.heartbeatMs; if (typeof value.agentId !== "string" || Buffer.byteLength(value.agentId, "utf8") === 0 || Buffer.byteLength(value.agentId, "utf8") > 256 || !Number.isSafeInteger(generationValue) || (generationValue as number) < 1 || !Number.isSafeInteger(connectionGenerationValue) || (connectionGenerationValue as number) < 1 || !Number.isSafeInteger(heartbeatMsValue) || (heartbeatMsValue as number) < 1 || !Array.isArray(value.permissions) || value.permissions.length > 4096 || value.permissions.some((item) => typeof item !== "string" || Buffer.byteLength(item, "utf8") === 0 || Buffer.byteLength(item, "utf8") > 256)) throw new Error("PI_REGISTRATION_IDENTITY_INVALID"); const generation = generationValue as number; const connectionGeneration = connectionGenerationValue as number; const heartbeatMs = heartbeatMsValue as number; if (this.#options.token && (value.agentId !== this.#options.agentId || generation !== this.#options.generation)) throw new Error("PI_REGISTRATION_IDENTITY_MISMATCH"); this.bindIdentity(value.agentId, generation); if (this.#principal) this.#principal = { ...this.#principal, agentId: value.agentId, generation, permissions: [...value.permissions] }; return { agentId: value.agentId, generation, connectionGeneration, heartbeatMs, permissions: [...value.permissions] as string[] }; }
  nextAdapterSeq(): number { return ++this.#adapterSeq; }
  async heartbeat(state: PiSafeState): Promise<unknown> { return await this.request("agent.heartbeat", { adapterSeq: this.nextAdapterSeq(), state: { sessionId: state.sessionId, activity: state.activity, turnIndex: state.turnIndex, contextPercent: state.contextPercent, currentTool: state.currentTool } }); }
  close(): void { this.#socket?.destroy(); this.#socket = undefined; this.#connected = false; for (const waiter of this.#pending.values()) waiter.reject(new Error("AGENT_DISCONNECTED")); this.#pending.clear(); }
  private failClosed(error = new Error("BROKER_PROTOCOL_INVALID")): void { const socket = this.#socket; this.#socket = undefined; this.#connected = false; socket?.destroy(); for (const waiter of this.#pending.values()) waiter.reject(error); this.#pending.clear(); }
  private timeout(value: number): number { if (!Number.isSafeInteger(value) || value < 100 || value > MAX_TIMEOUT_MS) throw new Error("INVALID_REQUEST"); return value; }
  private async handleServerRequest(frame: Record<string, unknown>): Promise<void> {
    const socket = this.#socket; if (!socket) return; let id: string;
    try { if (frame.v !== 1 || frame.type !== "server_request" || typeof frame.id !== "string" || frame.id.length === 0 || frame.id.length > 256 || /[\u0000-\u001f\u007f]/u.test(frame.id) || typeof frame.method !== "string" || frame.method.length === 0 || frame.method.length > 128 || /[\u0000-\u001f\u007f]/u.test(frame.method) || !frame.params || typeof frame.params !== "object" || Array.isArray(frame.params) || Object.keys(frame.params).length > 64 || Buffer.byteLength(JSON.stringify(frame.params), "utf8") > 262_144) throw new Error("INVALID_REQUEST"); id = frame.id; } catch { const candidate = typeof frame.id === "string" && frame.id.length <= 256 ? frame.id : createId("evt"); socket.write(encodeFrame({ v: 1, type: "server_response", id: candidate, ok: false, error: { code: "INVALID_REQUEST", message: "The server request was invalid." } })); return; }
    if (this.#serverRequestIds.has(id)) { socket.write(encodeFrame({ v: 1, type: "server_response", id, ok: false, error: { code: "DUPLICATE_REQUEST", message: "The server request was already handled." } })); return; }
    if (this.#serverRequestIds.size >= 256) { this.failClosed(); return; } this.#serverRequestIds.add(id);
    try { const request = { id, method: frame.method as string, params: frame.params as Record<string, unknown> }; const control = request.method.startsWith("control.") ? this.#options.onControlRequest : this.#options.onServerRequest; if (!control) throw new Error("PI_METHOD_UNAVAILABLE"); const result = await control(request); if (this.#socket === socket) socket.write(encodeFrame({ v: 1, type: "server_response", id, ok: true, result })); } catch (error) { const code = error instanceof Error && /^[A-Z0-9_]{1,64}$/u.test(error.message) ? error.message : "REQUEST_FAILED"; if (this.#socket === socket) socket.write(encodeFrame({ v: 1, type: "server_response", id, ok: false, error: { code, message: "The Pi adapter rejected the request." } })); }
  }
  private async raw(frame: unknown, timeoutMs?: number): Promise<unknown> { if (!this.#socket) throw new Error("AGENT_DISCONNECTED"); const id = (frame as Record<string, unknown>).id as string; const timeout = this.timeout(timeoutMs ?? ((frame as Record<string, unknown>).type === "hello" ? (this.#options.helloTimeoutMs ?? DEFAULT_HELLO_TIMEOUT_MS) : (this.#options.requestTimeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS))); return await new Promise((resolve, reject) => { const socket = this.#socket; const timer = setTimeout(() => { this.#pending.delete(id); socket?.destroy(); reject(new Error("BROKER_TIMEOUT")); }, timeout); timer.unref?.(); this.#pending.set(id, { resolve: (value) => { clearTimeout(timer); resolve(value); }, reject: (error) => { clearTimeout(timer); reject(error); } }); try { socket!.write(encodeFrame(frame)); } catch (error) { this.#pending.delete(id); clearTimeout(timer); reject(error instanceof Error ? error : new Error("BROKER_REQUEST_FAILED")); } }); }
}
