import { boundedSecretFree, DEFAULT_PARENT_TOOL_LIMITS, ParentToolService, type ParentToolName, type ParentToolRequest, type ToolPrincipal } from "./parent-tools.js";
import { isParentToolRequest, PARENT_TOOL_NAMES } from "./parent-tool-schema.js";
import type { PiAdapter, } from "./adapter.js";
import type { PiBrokerClient } from "./broker-client.js";
import type { PiApiLike, PiContextLike } from "./types.js";

const MAX_BODY_BYTES = 262_144;
const MAX_TEXT_BYTES = 16_384;
const resultSchema = {
  type: "object", additionalProperties: false,
  required: ["schemaVersion", "status", "summary", "findings", "changedFiles", "commandsRun", "tests", "commits", "artifacts", "unresolved", "questions", "recommendedNextAction"],
  properties: {
    schemaVersion: { type: "integer", const: 1 }, status: { type: "string", enum: ["succeeded", "failed", "cancelled"] },
    summary: { type: "string", maxLength: MAX_TEXT_BYTES }, findings: { type: "array", maxItems: 256 }, changedFiles: { type: "array", maxItems: 4096 }, commandsRun: { type: "array", maxItems: 256 }, tests: { type: "array", maxItems: 256 }, commits: { type: "array", maxItems: 256 }, artifacts: { type: "array", maxItems: 128 }, unresolved: { type: "array", maxItems: 256 }, questions: { type: "array", maxItems: 256 }, recommendedNextAction: { type: ["string", "null"], maxLength: MAX_TEXT_BYTES },
  },
};
const questionSchema = {
  type: "object", additionalProperties: false,
  required: ["schemaVersion", "prompt", "context", "options", "allowFreeform", "defaultOptionId", "timeoutMs"],
  properties: {
    schemaVersion: { type: "integer", const: 1 }, prompt: { type: "string", minLength: 1, maxLength: MAX_TEXT_BYTES }, context: { type: ["string", "null"], maxLength: MAX_TEXT_BYTES },
    options: { type: "array", minItems: 1, maxItems: 8, items: { type: "object", additionalProperties: false, required: ["id", "label", "description"], properties: { id: { type: "string", maxLength: 256 }, label: { type: "string", maxLength: 4096 }, description: { type: ["string", "null"], maxLength: 4096 } } } },
    allowFreeform: { type: "boolean" }, defaultOptionId: { type: ["string", "null"] }, timeoutMs: { type: "integer", minimum: 1, maximum: 900_000 },
  },
};
const parentInputKeys: Readonly<Record<ParentToolName, readonly string[]>> = Object.freeze({ delegate: ["mode", "title", "parentAgentId", "steps", "wait", "waitUntil", "timeoutMs", "failureMode", "dryRun"], agent_spawn: ["parentAgentId", "task", "profileId", "project", "isolation", "budget", "wait"], agent_list: ["ids", "parentAgentId", "managed", "state", "profileId", "taskId", "workspaceId", "connected", "include", "maxBytes", "cursor", "limit"], agent_get: ["agentId", "include", "maxBytes"], agent_prompt: ["agentId", "message", "delivery", "timeoutMs", "createTask", "task", "profileId", "project", "isolation", "budget"], agent_steer: ["agentId", "message", "delivery", "runId", "assignmentGeneration"], agent_wait: ["agentId", "taskId", "runId", "until", "timeoutMs"], agent_result: ["taskId", "resultId", "include", "maxBytes"], agent_answer: ["questionId", "answer"], agent_interrupt: ["agentId", "runId", "assignmentGeneration", "reason"], agent_stop: ["agentId", "runId", "assignmentGeneration", "reason", "force"], agent_close: ["agentId", "runId", "assignmentGeneration", "reason", "confirm"], task_list: ["parentAgentId", "state", "profileId", "workspaceId", "include", "maxBytes", "cursor", "limit"], task_get: ["taskId", "include", "maxBytes"], task_collect: ["taskIds", "select", "maxBytes"], task_cancel: ["taskId", "reason", "cascade"] });
function validateNested(value: unknown, depth = 0): void { if (depth > 6) throw new Error("LIMIT_EXCEEDED"); if (typeof value === "string") { if (Buffer.byteLength(value, "utf8") > MAX_TEXT_BYTES || /[\u0000-\u001f\u007f]/u.test(value)) throw new Error("INVALID_REQUEST"); return; } if (Array.isArray(value)) { if (value.length > 64) throw new Error("LIMIT_EXCEEDED"); for (const item of value) validateNested(item, depth + 1); return; } if (value && typeof value === "object") { const entries = Object.entries(value); if (entries.length > 32) throw new Error("LIMIT_EXCEEDED"); for (const [key, item] of entries) { if (Buffer.byteLength(key, "utf8") > 256 || /(?:token|secret|password|cookie|credential|private.?key|api.?key)/iu.test(key)) throw new Error("INVALID_REQUEST"); validateNested(item, depth + 1); } } }
const parentRequired: Readonly<Partial<Record<ParentToolName, readonly string[]>>> = Object.freeze({ delegate: ["mode", "title", "steps", "wait", "waitUntil", "timeoutMs", "failureMode", "dryRun"], agent_spawn: ["task", "profileId", "project", "isolation", "budget", "wait"], agent_get: ["agentId"], agent_prompt: ["agentId", "message", "delivery", "timeoutMs"], agent_steer: ["agentId", "message", "delivery"], agent_wait: ["agentId", "taskId", "runId", "until", "timeoutMs"], agent_result: ["taskId"], agent_answer: ["questionId", "answer"], agent_interrupt: ["agentId"], agent_stop: ["agentId", "reason"], agent_close: ["agentId", "confirm"], task_get: ["taskId"], task_collect: ["taskIds"], task_cancel: ["taskId", "reason", "cascade"] });
function validateParentInput(tool: ParentToolName, input: Record<string, unknown>): void { const keys = new Set(parentInputKeys[tool]); if (Object.keys(input).some((key) => !keys.has(key)) || (parentRequired[tool] ?? []).some((key) => !Object.hasOwn(input, key))) throw new Error("INVALID_REQUEST"); for (const [key, value] of Object.entries(input)) { if (["wait", "dryRun", "managed", "connected", "force", "confirm", "createTask", "cascade"].includes(key) && typeof value !== "boolean") throw new Error("INVALID_REQUEST"); if (["timeoutMs", "maxBytes", "limit", "assignmentGeneration"].includes(key) && (!Number.isSafeInteger(value) || (value as number) < 1)) throw new Error("INVALID_REQUEST"); if (["ids", "taskIds", "include", "select", "steps", "waitUntil", "until"].includes(key) && !Array.isArray(value)) throw new Error("INVALID_REQUEST"); if (key === "steps" && (value as unknown[]).length > 32) throw new Error("LIMIT_EXCEEDED"); if (key === "task") { if (!value || typeof value !== "object" || Array.isArray(value) || !Object.hasOwn(value, "title") || !Object.hasOwn(value, "objective")) throw new Error("INVALID_REQUEST"); } if (key === "answer") { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== 1 || (!Object.hasOwn(value, "optionId") && !Object.hasOwn(value, "text"))) throw new Error("INVALID_REQUEST"); } } validateNested(input); if (Buffer.byteLength(JSON.stringify(input), "utf8") > 65_536) throw new Error("LIMIT_EXCEEDED"); }
function schemaForKey(key: string): unknown { if (["wait", "dryRun", "managed", "connected", "force", "confirm", "createTask", "cascade"].includes(key)) return { type: "boolean" }; if (["timeoutMs", "maxBytes", "limit", "assignmentGeneration"].includes(key)) return { type: "integer", minimum: 1, maximum: 1_800_000 }; if (["mode"].includes(key)) return { type: "string", enum: ["single", "parallel", "chain", "dag", "implement_review_fix"] }; if (["delivery"].includes(key)) return { type: "string", enum: ["normal", "steer", "follow_up"] }; if (["failureMode"].includes(key)) return { type: "string", enum: ["fail_fast", "collect_all"] }; if (["waitUntil"].includes(key)) return { type: "array", maxItems: 8, items: { type: "string", enum: ["terminal", "blocked"] } }; if (["until"].includes(key)) return { type: "array", minItems: 1, maxItems: 8, items: { type: "string", enum: ["succeeded", "failed", "cancelled", "timed_out", "blocked"] } }; if (["ids", "taskIds", "include", "select"].includes(key)) return { type: "array", maxItems: 64, items: { type: "string", minLength: 1, maxLength: 256 } }; if (["steps"].includes(key)) return { type: "array", minItems: 1, maxItems: 32, items: { type: "object", additionalProperties: false, required: ["key", "profileId", "title", "objective"], properties: { key: { type: "string", maxLength: 256 }, profileId: { type: "string", maxLength: 256 }, title: { type: "string", maxLength: MAX_TEXT_BYTES }, objective: { type: "string", maxLength: MAX_TEXT_BYTES }, dependsOn: { type: "array", maxItems: 64, items: { type: "string", maxLength: 256 } } } } }; if (["task"].includes(key)) return { type: "object", additionalProperties: false, required: ["title", "objective"], properties: { title: { type: "string", minLength: 1, maxLength: MAX_TEXT_BYTES }, objective: { type: "string", minLength: 1, maxLength: MAX_TEXT_BYTES }, constraints: { type: "array", maxItems: 64, items: { type: "string", maxLength: MAX_TEXT_BYTES } } } }; if (["project"].includes(key)) return { type: "object", additionalProperties: false, required: ["cwd"], properties: { cwd: { type: "string", maxLength: 4096 }, trusted: { type: "boolean" } } }; if (["isolation"].includes(key)) return { type: "object", additionalProperties: false, required: ["mode"], properties: { mode: { type: "string", enum: ["shared-readonly", "worktree"] } } }; if (["budget"].includes(key)) return { type: "object", additionalProperties: false, required: ["wallTimeMs"], properties: { wallTimeMs: { type: "integer", minimum: 1, maximum: 86_400_000 } } }; if (["answer"].includes(key)) return { oneOf: [{ type: "object", additionalProperties: false, required: ["optionId"], properties: { optionId: { type: "string", minLength: 1, maxLength: 256 } } }, { type: "object", additionalProperties: false, required: ["text"], properties: { text: { type: "string", minLength: 1, maxLength: MAX_TEXT_BYTES } } }] }; return { type: "string", maxLength: MAX_TEXT_BYTES }; }
function parentInputSchema(tool: ParentToolName): unknown { return { type: "object", additionalProperties: false, maxProperties: 32, properties: Object.fromEntries(parentInputKeys[tool].map((key) => [key, schemaForKey(key)])) }; }

interface ToolDefinition { name: string; label: string; description: string; parameters: unknown; execute: (toolCallId: string, params: Record<string, unknown>, signal: AbortSignal, onUpdate: unknown, context: PiContextLike) => Promise<{ content: Array<{ type: "text"; text: string }>; details?: unknown; isError?: boolean }>; }
export interface PiToolBinding { adapter: PiAdapter | undefined; client: PiBrokerClient | undefined; registered?: boolean; }
function register(api: PiApiLike, definition: ToolDefinition): void { api.registerTool?.(definition); }
function textResult(value: unknown): { content: Array<{ type: "text"; text: string }>; details: unknown } { const safe = boundedSecretFree(value); const encoded = JSON.stringify(safe); if (Buffer.byteLength(encoded, "utf8") <= DEFAULT_PARENT_TOOL_LIMITS.maxResponseBytes) return { content: [{ type: "text", text: encoded }], details: safe }; const preview = boundedSecretFree(value, { ...DEFAULT_PARENT_TOOL_LIMITS, maxItems: 8, maxTextBytes: 1024 }); const previewText = JSON.stringify(preview); const details = Buffer.byteLength(previewText, "utf8") <= DEFAULT_PARENT_TOOL_LIMITS.maxResponseBytes ? { truncated: true, preview } : { truncated: true }; return { content: [{ type: "text", text: JSON.stringify(details) }], details }; }
function assertBoundedBody(value: Record<string, unknown>): void { const encoded = JSON.stringify(value); if (Buffer.byteLength(encoded, "utf8") > MAX_BODY_BYTES) throw new Error("LIMIT_EXCEEDED"); }
function stripModelIdentity(input: Record<string, unknown>): Record<string, unknown> {
  const copy = { ...input }; delete copy.principalId; delete copy.parentAgentId; delete copy.principal;
  return copy;
}

export function registerManagedChildTools(api: PiApiLike, adapterOrBinding: PiAdapter | PiToolBinding, client?: PiBrokerClient): void {
  const binding: PiToolBinding = client ? { adapter: adapterOrBinding as PiAdapter, client } : adapterOrBinding as PiToolBinding;
  register(api, { name: "orchestrator_result", label: "Publish orchestrator result", description: "Publish the single structured terminal result for the current managed task. Correlation identity is supplied by the adapter.", parameters: resultSchema, async execute(_id, params, signal) {
    if (signal.aborted) throw new Error("CANCELLED");
    const adapter = binding.adapter; const client = binding.client; if (!adapter || !client || !client.connected) throw new Error("AGENT_DISCONNECTED"); const assignment = adapter.assignmentForTools(); if (!assignment) throw new Error("RUN_MISMATCH");
    assertBoundedBody(params);
    const result = await client.request("result.publish", { agentId: assignment.agentId, taskId: assignment.taskId, runId: assignment.runId, assignmentGeneration: assignment.assignmentGeneration, result: params });
    return textResult(result);
  } });
  register(api, { name: "orchestrator_ask", label: "Ask orchestrator question", description: "Ask one blocking structured question for the current managed task. Correlation identity is supplied by the adapter.", parameters: questionSchema, async execute(_id, params, signal) {
    if (signal.aborted) throw new Error("CANCELLED");
    const adapter = binding.adapter; const client = binding.client; if (!adapter || !client || !client.connected) throw new Error("AGENT_DISCONNECTED"); const assignment = adapter.assignmentForTools(); if (!assignment) throw new Error("RUN_MISMATCH");
    assertBoundedBody(params);
    const result = await client.request("question.open", { agentId: assignment.agentId, taskId: assignment.taskId, runId: assignment.runId, assignmentGeneration: assignment.assignmentGeneration, question: params });
    return textResult(result);
  } });
}

export function registerParentTools(api: PiApiLike, adapterOrBinding: PiAdapter | PiToolBinding, client?: PiBrokerClient): void {
  const binding: PiToolBinding = client ? { adapter: adapterOrBinding as PiAdapter, client } : adapterOrBinding as PiToolBinding;
  const principalFromClient = (): ToolPrincipal => { const adapter = binding.adapter; const client = binding.client; if (!adapter || !client || !client.connected) throw new Error("AGENT_DISCONNECTED"); const p = client.principal; return { id: p?.id ?? `pi:${adapter.safeState().agentId}`, kind: "pi_parent", agentId: adapter.safeState().agentId, permissions: p?.permissions ?? ["read:state", "delegate"] }; };
  const broker = { invoke: async (method: string, params: Record<string, unknown>, _principal: ToolPrincipal, idempotencyKey?: string) => { const client = binding.client; if (!client?.connected) throw new Error("AGENT_DISCONNECTED"); return client.request(method, params, idempotencyKey ? { idempotencyKey } : {}); } };
  const service = new ParentToolService(broker);
  const permissions = new Set(principalFromClient().permissions);
  for (const tool of PARENT_TOOL_NAMES) {
    if (tool === "delegate" && !permissions.has("delegate") && !permissions.has("manage:all")) continue;
    register(api, { name: tool, label: `Orchestrator ${tool}`, description: `Use broker method for ${tool}. The broker checks current state and parent scope on every call.`, parameters: { type: "object", additionalProperties: false, properties: { input: parentInputSchema(tool as ParentToolName), idempotencyKey: { type: "string", minLength: 1, maxLength: 256 } }, required: ["input"] }, async execute(_id, params, signal) {
      const raw = params.input; if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error("INVALID_REQUEST");
      const principal = principalFromClient(); const adapter = binding.adapter; const client = binding.client; if (!adapter || !client) throw new Error("AGENT_DISCONNECTED"); validateParentInput(tool as ParentToolName, raw as Record<string, unknown>);
      const request: ParentToolRequest = { tool: tool as ParentToolName, input: stripModelIdentity(raw as Record<string, unknown>), ...(typeof params.idempotencyKey === "string" ? { idempotencyKey: params.idempotencyKey } : {}) };
      if (!isParentToolRequest(request)) throw new Error("INVALID_REQUEST");
      const response = await service.execute(request, principal, signal); if (!response.ok) throw new Error(response.error?.code ?? "REQUEST_FAILED"); return textResult(response.result);
    } });
  }
}

export function registerOrchestratorTools(api: PiApiLike, binding: PiToolBinding, managed: boolean): void { if (managed) registerManagedChildTools(api, binding); else registerParentTools(api, binding); binding.registered = true; }
