import assert from "node:assert/strict";
import { createServer, type Socket } from "node:net";
import test from "node:test";
import { PiBrokerClient } from "../../src/pi/broker-client.js";
import { PiAdapter } from "../../src/pi/adapter.js";
import type { PiApiLike, PiContextLike } from "../../src/pi/types.js";
import { encodeFrame, NdjsonDecoder } from "../../src/shared/protocol/codec.js";

process.env.HERDR_PANE_ID = "p-1"; process.env.HERDR_TERMINAL_ID = "t-1";
const state = { agentId: "agt_adopted", generation: 3, sessionId: "pi-session", idle: false, pendingMessages: 0, activity: "working" as const, activeTools: ["read"], capabilities: { core: true, prompt: true, steer: true, followUp: true, abort: true, compact: true, model: true, thinking: true, tools: true, toolExpansion: false } };
function adapter(): PiAdapter { const api: PiApiLike = { on: () => undefined, registerCommand: () => undefined, sendUserMessage: async () => undefined, setModel: () => true, setThinkingLevel: () => undefined, getAllowedThinkingLevels: () => ["medium"], getAllTools: () => [{ name: "read" }], setActiveTools: () => undefined, getActiveTools: () => ["read"] }; const context: PiContextLike = { ui: {}, cwd: "/tmp", sessionManager: { getSessionId: () => state.sessionId }, modelRegistry: { find: () => ({ provider: "fake", id: "model" }) }, isIdle: () => false, hasPendingMessages: () => false, abort: () => undefined, compact: (options) => options?.onComplete?.(), model: { provider: "fake", id: "model" }, thinkingLevel: "medium" }; return new PiAdapter(api, context, state.agentId, state.generation); }
async function server(handler: (frame: Record<string, unknown>, socket: Socket) => void): Promise<{ path: string; close: () => Promise<void> }> { const path = `/tmp/pi-client-${process.pid}-${Math.random().toString(36).slice(2)}.sock`; const srv = createServer((socket) => { const decoder = new NdjsonDecoder<unknown>((value) => value); socket.on("data", (data) => { for (const item of decoder.push(data)) if (item.ok && item.value && typeof item.value === "object") handler(item.value as Record<string, unknown>, socket); }); }); await new Promise<void>((resolve, reject) => { srv.once("error", reject); srv.listen(path, resolve); }); return { path, close: async () => { await new Promise<void>((resolve) => srv.close(() => resolve())); } }; }
function hello(frame: Record<string, unknown>): unknown { return { v: 1, type: "hello_result", id: frame.id, ok: true, broker: { version: "test", status: "healthy", lastEventSeq: 7 }, principal: { id: "prn_parent", kind: "pi_parent", permissions: ["read:state", "delegate"] }, limits: { maxLineBytes: 1_048_576 } }; }

test("PiBrokerClient accepts real hello_result and binds adopted registration identity", async () => { const requests: Record<string, unknown>[] = []; const fake = await server((frame, socket) => { if (frame.type === "hello") socket.write(encodeFrame(hello(frame))); else { requests.push(frame); socket.write(encodeFrame({ v: 1, type: "response", id: frame.id, method: frame.method, ok: true, result: { agentId: "agt_broker", generation: 4, connectionGeneration: 1, heartbeatMs: 5000, permissions: ["read:state"] } })); } }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: "pi-session", secret: "secret" }); await client.connect(); const registration = await client.register(state); await client.request("agent.get", { agentId: "agt_broker" }, { idempotencyKey: "idem_1" }); assert.equal(registration.agentId, "agt_broker"); assert.deepEqual(requests[0]?.params, { adapterVersion: "0.1.0", herdr: { paneId: "p-1", terminalId: "t-1", detectedKind: "pi" }, pi: { sessionId: "pi-session", capabilities: state.capabilities, state: { activity: "working", idle: false, pendingMessages: 0 } } }); assert.equal(client.principal?.id, "prn_parent"); assert.equal(client.principal?.agentId, "agt_broker"); assert.equal(requests[1]?.idempotencyKey, "idem_1"); assert.equal(Object.hasOwn((requests[1]?.params ?? {}) as Record<string, unknown>, "idempotencyKey"), false); client.close(); await fake.close(); });

test("PiBrokerClient emits the exact managed registration frame", async () => { const requests: Record<string, unknown>[] = []; const fake = await server((frame, socket) => { if (frame.type === "hello") socket.write(encodeFrame(hello(frame))); else { requests.push(frame); socket.write(encodeFrame({ v: 1, type: "response", id: frame.id, method: frame.method, ok: true, result: { agentId: "agt_managed", generation: 1, connectionGeneration: 2, heartbeatMs: 5000, permissions: ["read:state"] } })); } }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: "pi-session", agentId: "agt_managed", generation: 1, token: "token_value" }); await client.connect(); await client.register(state); assert.deepEqual(requests[0]?.params, { adapterVersion: "0.1.0", agentId: "agt_managed", generation: 1, herdr: { paneId: "p-1", terminalId: "t-1", detectedKind: "pi" }, pi: { sessionId: "pi-session", capabilities: state.capabilities, state: { activity: "working", idle: false, pendingMessages: 0 } } }); client.close(); await fake.close(); });

test("PiBrokerClient rejects a hello_result with a wrong correlated id", async () => { const fake = await server((frame, socket) => { if (frame.type === "hello") socket.write(encodeFrame({ ...(hello(frame) as Record<string, unknown>), id: "wrong" })); }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: "pi-session", secret: "secret" }); const result = client.connect(); await assert.rejects(result, /AGENT_DISCONNECTED|BROKER_HELLO_INVALID/); client.close(); await fake.close(); });

test("PiAdapter rejects wrong control identity and unsupported capabilities", async () => { const pi = adapter(); await assert.rejects(() => pi.handleControl("control.set_tools", { agentId: "wrong", generation: state.generation, piSessionId: state.sessionId, tools: ["read"] }), /PI_IDENTITY_MISMATCH/); await assert.rejects(() => pi.handleControl("control.set_tool_expansion", { agentId: state.agentId, generation: state.generation, piSessionId: state.sessionId, name: "read", expanded: true }), /PI_CAPABILITY_MISSING/); });


test("question waiter binds early delivery and rejects duplicate or mismatched delivery", async () => { const fake = await server((frame, socket) => { if (frame.type === "hello") socket.write(encodeFrame(hello(frame))); }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: "pi-session", secret: "secret" }); await client.connect(); const waiter = client.registerQuestionWaiter("tool-1", "run-1", 10_000); assert.equal(client.resolveQuestionDelivery("q-1", "run-1", "tool-1", { state: "answered" }), true); assert.equal(client.resolveQuestionDelivery("q-1", "run-1", "tool-1", { state: "answered" }), false); await assert.doesNotReject(waiter); client.bindQuestionWaiter("tool-1", "q-1"); const mismatch = client.registerQuestionWaiter("tool-2", "run-2", 10_000); assert.equal(client.resolveQuestionDelivery("q-2", "run-2", "tool-2", { state: "answered" }), true); assert.throws(() => client.bindQuestionWaiter("tool-2", "q-3"), /QUESTION_DELIVERY_INVALID/); client.discardQuestionWaiter("tool-2"); await assert.doesNotReject(mismatch); await assert.rejects(client.registerQuestionWaiter("tool-3", "run-3", 9_999), /INVALID_REQUEST/); client.close(); await fake.close(); });
test("PiBrokerClient gates coalesced registration and server request until explicit readiness", async () => { const delivered: string[] = []; const fake = await server((frame, socket) => { if (frame.type === "hello") socket.write(encodeFrame(hello(frame))); else if (frame.method === "agent.register_adopted") { socket.write(encodeFrame({ v: 1, type: "response", id: frame.id, method: frame.method, ok: true, result: { agentId: "agt_broker", generation: 4, connectionGeneration: 1, heartbeatMs: 5000, permissions: ["read:state"] } })); socket.write(encodeFrame({ v: 1, type: "server_request", id: "srv-ready", method: "control.abort", params: { agentId: "agt_broker", generation: 4, piSessionId: "pi-session", connectionGeneration: 1 } })); } }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: "pi-session", secret: "secret", onControlRequest: async (request) => { delivered.push(request.id); return { ok: true }; } }); await client.connect(); await client.register(state); await new Promise((resolve) => setTimeout(resolve, 10)); assert.deepEqual(delivered, []); client.markRegistrationReady(); await new Promise((resolve) => setTimeout(resolve, 20)); assert.deepEqual(delivered, ["srv-ready"]); client.close(); await fake.close(); });
test("PiBrokerClient rejects and clears a question waiter on socket disconnect", async () => { let peer: import("node:net").Socket | undefined; const fake = await server((frame, socket) => { peer = socket; if (frame.type === "hello") socket.write(encodeFrame(hello(frame))); }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: "pi-session", secret: "secret" }); await client.connect(); const waiter = client.registerQuestionWaiter("tool-disconnect", "run-disconnect", 10_000); peer?.destroy(); await assert.rejects(waiter, /AGENT_DISCONNECTED/); client.close(); await fake.close(); });
test("PiBrokerClient routes control server requests with identity guards and server_response", async () => { const seen: Record<string, unknown>[] = []; const pi = adapter(); const fake = await server((frame, socket) => { if (frame.type === "hello") { socket.write(encodeFrame(hello(frame))); setTimeout(() => { socket.write(encodeFrame({ v: 1, type: "server_request", id: "control-1", method: "control.set_tools", params: { agentId: state.agentId, generation: state.generation, piSessionId: state.sessionId, tools: ["read"] } })); socket.write(encodeFrame({ v: 2, type: "server_request", id: "bad-1", method: "control.set_tools", params: {} })); }, 5); } else if (frame.type === "server_response") seen.push(frame); }); const client = new PiBrokerClient({ socketPath: fake.path, sessionKey: "session", piSessionId: state.sessionId, secret: "secret", onControlRequest: (request) => pi.handleControl(request.method, request.params) }); await client.connect(); await new Promise((resolve) => setTimeout(resolve, 30)); await new Promise((resolve) => setTimeout(resolve, 30)); assert.equal(client.connected, false); client.close(); await fake.close(); });
