import assert from "node:assert/strict";
import test from "node:test";
import { PiAdapter } from "../../src/pi/adapter.js";
import type { PiApiLike, PiContextLike } from "../../src/pi/types.js";

function makeAdapter() { let idle = true; const api: PiApiLike = { on: () => undefined, registerCommand: () => undefined, sendUserMessage: async () => { idle = false; }, setActiveTools: () => undefined, getActiveTools: () => [] }; const context: PiContextLike = { ui: {}, cwd: "/tmp", sessionManager: { getSessionId: () => "pi-session" }, modelRegistry: {}, isIdle: () => idle, hasPendingMessages: () => false, abort: () => undefined, compact: (options) => options?.onComplete?.() }; const adapter = new PiAdapter(api, context, "agt_1", 1); return { adapter, setIdle: (value: boolean) => { idle = value; } }; }
const assignment = { id: "asg_1", taskId: "tsk_1", runId: "run_1", agentId: "agt_1", generation: 1, assignmentGeneration: 2, piSessionId: "pi-session", objective: "objective", constraints: [], deadline: "2030-01-01T00:00:00Z" };

test("lifecycle frames use the frozen nested contract and retain only the active opaque cycle", async () => { const { adapter, setIdle } = makeAdapter(); adapter.bindIdentity("agt_1", 1, 4); await adapter.deliver(assignment); adapter.onLifecycle({ type: "agent_start", agentId: "agt_1", generation: 1, piSessionId: "pi-session" }); const bound = adapter.onLifecycle({ type: "turn_start", agentId: "agt_1", generation: 1, piSessionId: "pi-session", turnIndex: 7, assignmentGeneration: 2 }); assert.equal(bound, "bound"); const started = adapter.lifecyclePayload("bound", { type: "turn_start", agentId: "agt_1", generation: 1, piSessionId: "pi-session", turnIndex: 7, assignmentGeneration: 2 }, 91); assert.deepEqual(started, { agentId: "agt_1", connectionGeneration: 4, adapterSeq: 91, event: "turn_start", piSessionId: "pi-session", turnIndex: 7, agentCycleId: started?.agentCycleId, assignment: { assignmentId: "asg_1", generation: 2 }, safeData: { toolName: null, contextPercent: null } }); assert.equal(typeof started?.agentCycleId, "string"); setIdle(false); const settled = adapter.onLifecycle({ type: "agent_settled", agentId: "agt_1", generation: 1, piSessionId: "pi-session", assignmentGeneration: 2 }); assert.equal(settled, "settled"); const terminal = adapter.lifecyclePayload("settled", { type: "agent_settled", agentId: "agt_1", generation: 1, piSessionId: "pi-session", assignmentGeneration: 2 }, 92); assert.equal(terminal?.event, "agent_settled"); assert.equal(terminal?.turnIndex, 7); adapter.clearSettledCycle(); setIdle(true); await adapter.deliver({ ...assignment, id: "asg_2", runId: "run_2", assignmentGeneration: 3 }); const stale = adapter.onLifecycle({ type: "agent_settled", agentId: "agt_1", generation: 1, piSessionId: "pi-session", assignmentGeneration: 2 }); assert.equal(stale, "manual"); });
